spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
  flyway:
    baseline-on-migrate: true
  config:
    import: file:src/main/resources/env.yaml
  datasource:
    hikari:
      minimum-idle: 80
      maximum-pool-size: 160