spring:
  jpa:
    open-in-view: false
    show-sql: true
  flyway:
    baseline-on-migrate: true
  config:
    import: file:src/main/resources/env.yaml
  datasource:
    hikari:
      minimum-idle: 80
      maximum-pool-size: 160
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs